// SPDX-License-Identifier: GPL-3.0-only

#ifndef HARMONY_HALO_DATA_SOUNDS
#define HARMONY_HALO_DATA_SOUNDS

#include <string>

namespace Harmony::HaloData {
    enum MultiplayerSound : std::uint32_t {
        MULTIPLAYER_SOUND_PLAYBALL,
        MULTIPLAYER_SOUND_GAME_OVER,
        MULTIPLAYER_SOUND_ONE_MINUTE_TO_WIN,
        MULTIPLAYER_SOUND_THIRTY_SECONDS_TO_WIN,
        MULTIPLAYER_SOUND_RED_TEAM_ONE_MINUTE_TO_WIN,
        MULTIPLAYER_SOUND_RED_TEAM_THIRTY_SECONDS_TO_WIN,
        MULTIPLAYER_SOUND_BLUE_TEAM_ONE_MINUTE_TO_WIN,
        MULTIPLAYER_SOUND_BLUE_TEAM_THIRTY_SECONDS_TO_WIN,
        MULTIPLAYER_SOUND_RED_TEAM_FLAG_TAKEN,
        MULTIPLAYER_SOUND_RED_TEAM_FLAG_RETURNED,
        MULTIPLAYER_SOUND_RED_TEAM_FLAG_CAPTURED,
        MULTIPLAYER_SOUND_BLUE_TEAM_FLAG_TAKEN,
        MULTIPLAYER_SOUND_BLUE_TEAM_FLAG_RETURNED,
        MULTIPLAYER_SOUND_BLUE_TEAM_FLAG_CAPTURED,
        MULTIPLAYER_SOUND_DOUBLE_KILL,
        MULTIPLAYER_SOUND_TRIPLE_KILL,
        MULTIPLAYER_SOUND_KILLTACULAR,
        MULTIPLAYER_SOUND_RUNNING_RIOT,
        MULTIPLAYER_SOUND_KILLING_SPREE,
        MULTIPLAYER_SOUND_ODDBALL,
        MULTIPLAYER_SOUND_RACE,
        MULTIPLAYER_SOUND_SLAYER,
        MULTIPLAYER_SOUND_CAPTURE_THE_FLAG,
        MULTIPLAYER_SOUND_WARTHOG,
        MULTIPLAYER_SOUND_GHOST,
        MULTIPLAYER_SOUND_SCORPION,
        MULTIPLAYER_SOUND_COUNTDOWN_TIMER,
        MULTIPLAYER_SOUND_TELEPORTER_ACTIVATE,
        MULTIPLAYER_SOUND_FLAG_FAILURE,
        MULTIPLAYER_SOUND_COUNTDOWN_FOR_RESPAWN,
        MULTIPLAYER_SOUND_HILL_MOVE,
        MULTIPLAYER_SOUND_PLAYER_RESPAWN,
        MULTIPLAYER_SOUND_KING_OF_THE_HILL,
        MULTIPLAYER_SOUND_ODD_BALL,
        MULTIPLAYER_SOUND_TEAM_RACE,
        MULTIPLAYER_SOUND_TEAM_SLAYER,
        MULTIPLAYER_SOUND_TEAM_KING_OF_THE_HILL,
        MULTIPLAYER_SOUND_BLUE_TEAM_CAPTURE_THE_FLAG,
        MULTIPLAYER_SOUND_RED_TEAM_CAPTURE_THE_FLAG,
        MULTIPLAYER_SOUND_CONTEST,
        MULTIPLAYER_SOUND_CONTROL,
        MULTIPLAYER_SOUND_HILL_OCCUPIED,
        MULTIPLAYER_SOUND_COUNTDOWN_TIMER_END,
        MULTIPLAYER_SOUND_TING,

        MULTIPLAYER_SOUND_CUSTOM_1,
        MULTIPLAYER_SOUND_CUSTOM_2,
        MULTIPLAYER_SOUND_CUSTOM_3,
        MULTIPLAYER_SOUND_CUSTOM_4,
        MULTIPLAYER_SOUND_CUSTOM_5,
        MULTIPLAYER_SOUND_CUSTOM_6,
        MULTIPLAYER_SOUND_CUSTOM_7,
        MULTIPLAYER_SOUND_CUSTOM_8,
        MULTIPLAYER_SOUND_CUSTOM_9,
        MULTIPLAYER_SOUND_CUSTOM_10,
        MULTIPLAYER_SOUND_CUSTOM_11,
        MULTIPLAYER_SOUND_CUSTOM_12,
        MULTIPLAYER_SOUND_CUSTOM_13,
        MULTIPLAYER_SOUND_CUSTOM_14,
        MULTIPLAYER_SOUND_CUSTOM_15,
        MULTIPLAYER_SOUND_CUSTOM_16
    };

    std::string string_from_multiplayer_sound(MultiplayerSound sound) noexcept;
}

#endif
